# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 848ab6bc2b7f515a00bcf701317919e4c4acc4b2f4129a35b4e8c00452ce0c4c1dffffb01723dd9274acc79da4b295665e62bafd6b0fdfd788ebed9108a739ac

test:
  secret_key_base: a3a89da67a59efe1fc9eef573b605f74c3af2af593e0003b902073d1412d0eceb342174afc2cfcf4f0c70faf545f923ee3cd53666e9998ac0b1bea3d351506b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
